const path = require("path");

const express = require("express");
const bodyParser = require("body-parser");
const mongoose = require("mongoose");
const session = require("express-session");
// this library is used to store the sessions generated by express-session to mongodb
const MongoDbStore = require("connect-mongodb-session")(session);
const csrf = require("csurf");
// used to show flash messages to the user
const flash = require("connect-flash");
// read .env file and make the entries available in process.env global variables.
require("dotenv").config();

// const { engine } = require("express-handlebars");

const adminRoutes = require("./routes/admin");
const shopRoutes = require("./routes/shop");
const authRoutes = require("./routes/auth");

const User = require("./models/user");

const errorController = require("./controllers/error");

const MONGO_DB_URI = "mongodb://localhost:27017/shopping";

const app = express();

// By default the csrf token is stored in the session. You can override that to store the token in the cookie instead.
const csrfProtection = csrf();

// Tell express that we want to use handlebars as a templating engine
// The first param can be named anything.
// The second parameter is the function we imported above to initialize handlebars templating engine.
// app.engine(
//   "hbs",
//   engine({
//     extname: "hbs",
//     layoutsDir: "views/layouts/",
//     defaultLayout: "main-layout",
//   })
// );

// Set ejs as a templating engine
app.set("view engine", "ejs");
// The second parameter that you set here should match with the first parameter
// you set in the above code i.e. handlebars
// app.set("view engine", "hbs");

// Tell express that we are going to use a templating engine
// app.set("view engine", "pug");
/**
 * The below line5 is not necessary since the default views directory is views and
 * I am using views to store the templates. But if I use a different
 * name for the views folder for example, templates then I can set it for
 * the views key like
 * app.set('views', 'views');
 **/
app.set("views", "views");

//middlewares
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

// Configuration for the mongo db store used to save
// sessions generated into MongoDb
const sessionStore = MongoDbStore({
  uri: MONGO_DB_URI,
  collection: "sessions",
});

//session configuration
app.use(
  session({
    secret: "my secret",
    resave: false,
    saveUninitialized: false,
    store: sessionStore,
  })
);

// Add the csrf protection after we initialize the session
app.use(csrfProtection);

// Initialize flash after you initialize the session
app.use(flash());

app.use(express.static(path.join(__dirname, "public")));

app.use((req, res, next) => {
  console.log("In the middleware");
  next(); //Allows the request to continue to the next middleware in line
});

app.use((req, res, next) => {
  if (!req.session.user) {
    return next();
  }

  User.findById(req.session.user._id.toString())
    .then((user) => {
      req.user = user;
      next();
    })
    .catch((err) => {
      console.log(err);
      next();
    });
  //Allows the request to continue to the next middleware in line
});

// Add the csrf token and the variable that tells node.js that the user is logged in to every view.
app.use((req, res, next) => {
  // locals - is passed to every view in node.js
  // so this variables will be set for ever view that is rendered.
  res.locals.isAuthenticated = req.session.isLoggedIn === true;
  res.locals.csrfToken = req.csrfToken();
  next();
});

// the route can also be registed as a middleware
app.use("/admin", adminRoutes);
app.use(shopRoutes);
app.use(authRoutes);

//catch all middleware for 404
app.use(errorController.get404);

mongoose
  .connect(MONGO_DB_URI)
  .then((result) => {
    app.listen(3000);
  })
  .catch((err) => console.log(err));
